import sanitizeHtml from 'sanitize-html';
import { Prisma } from '@prisma/client';
import { prisma } from '../../lib/prisma.js';
import { serviceError } from '../../utils/service-error.js';

type Context = { ipAddress?: string; userAgent?: string };
type Input = { subjectId?: string | null; taskId?: string | null; title?: string; contentRichText?: string; tags?: string[] };
function sanitize(content: string) { return sanitizeHtml(content, { allowedTags: ['p', 'br', 'strong', 'em', 'u', 's', 'ul', 'ol', 'li', 'blockquote', 'h1', 'h2', 'h3', 'pre', 'code', 'a'], allowedAttributes: { a: ['href', 'target', 'rel'] }, allowedSchemes: ['http', 'https', 'mailto'] }); }
async function links(userId: string, input: Input) { if (input.subjectId) { const item = await prisma.subject.findFirst({ where: { id: input.subjectId, userId, deletedAt: null, semester: { deletedAt: null } } }); if (!item) throw serviceError('Subject not found', 404); } if (input.taskId) { const item = await prisma.task.findFirst({ where: { id: input.taskId, userId, deletedAt: null } }); if (!item) throw serviceError('Task not found', 404); } }
async function owned(userId: string, id: string) { const item = await prisma.note.findFirst({ where: { id, userId, deletedAt: null } }); if (!item) throw serviceError('Note not found', 404); return item; }
async function log(userId: string, action: string, entityId: string, context?: Context) { await prisma.activityLog.create({ data: { userId, action, entityType: 'note', entityId, ipAddress: context?.ipAddress, userAgent: context?.userAgent } }); }
export async function list(userId: string, query: { subjectId?: string; taskId?: string; search?: string; page: number; limit: number }) { const where: Prisma.NoteWhereInput = { userId, deletedAt: null, ...(query.subjectId ? { subjectId: query.subjectId } : {}), ...(query.taskId ? { taskId: query.taskId } : {}), ...(query.search ? { OR: [{ title: { contains: query.search, mode: 'insensitive' } }, { contentRichText: { contains: query.search, mode: 'insensitive' } }] } : {}) }; const [items, total] = await Promise.all([prisma.note.findMany({ where, orderBy: [{ isPinned: 'desc' }, { updatedAt: 'desc' }], skip: (query.page - 1) * query.limit, take: query.limit }), prisma.note.count({ where })]); return { items, pagination: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } }; }
export async function create(userId: string, input: { subjectId?: string | null; taskId?: string | null; title: string; contentRichText: string; tags?: string[] }, context?: Context) { await links(userId, input); const item = await prisma.note.create({ data: { ...input, userId, contentRichText: sanitize(input.contentRichText), tags: input.tags ?? [] } }); await log(userId, 'note.created', item.id, context); return item; }
export async function detail(userId: string, id: string) { return owned(userId, id); }
export async function update(userId: string, id: string, input: Input, context?: Context) { await owned(userId, id); await links(userId, input); const item = await prisma.note.update({ where: { id }, data: { ...input, ...(input.contentRichText !== undefined ? { contentRichText: sanitize(input.contentRichText) } : {}) } }); await log(userId, 'note.updated', id, context); return item; }
export async function pin(userId: string, id: string, isPinned: boolean | undefined, context?: Context) { const current = await owned(userId, id); const item = await prisma.note.update({ where: { id }, data: { isPinned: isPinned ?? !current.isPinned } }); await log(userId, 'note.pinned', id, context); return item; }
export async function remove(userId: string, id: string, context?: Context) { await owned(userId, id); await prisma.note.update({ where: { id }, data: { deletedAt: new Date() } }); await log(userId, 'note.deleted', id, context); return { id }; }
