import { Router } from 'express';
import multer from 'multer';
import { authenticate, authorize } from '../../middlewares/auth.js';
import { validateBody, validateQuery } from '../../middlewares/validate.js';
import { asyncHandler } from '../../utils/async-handler.js';
import * as c from './admin.controller.js';
import { sendSuccess } from '../../utils/http.js';
import { activityLogsQuery, feedbackQuery, feedbackUpdate, userUpdate, usersQuery } from './admin.schemas.js';
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024, files: 1 }, fileFilter: (_req, file, cb) => cb(null, file.mimetype.includes('spreadsheet') || file.mimetype.includes('excel')) });
export const adminRouter = Router(); adminRouter.use(authenticate, authorize('admin'));
adminRouter.get('/users', validateQuery(usersQuery), asyncHandler(c.users)); adminRouter.patch('/users/:id', validateBody(userUpdate), asyncHandler(c.updateUser)); adminRouter.get('/feedback', validateQuery(feedbackQuery), asyncHandler(c.feedback)); adminRouter.patch('/feedback/:id', validateBody(feedbackUpdate), asyncHandler(c.reply)); adminRouter.get('/activity-logs', validateQuery(activityLogsQuery), asyncHandler(c.logs)); adminRouter.get('/statistics', asyncHandler(c.statistics)); adminRouter.post('/subject-templates/import', upload.single('file'), asyncHandler(c.templates)); adminRouter.get('/system-content', asyncHandler(async (_req, res) => sendSuccess(res, 'System content fetched', { supported: false, message: 'System content storage is not configured yet.' })));
