import ExcelJS from 'exceljs';
import { prisma } from '../../lib/prisma.js';
import { serviceError } from '../../utils/service-error.js';
export async function users(query: { search?: string; page: number; limit: number }) { const where = query.search ? { OR: [{ email: { contains: query.search, mode: 'insensitive' as const } }, { fullName: { contains: query.search, mode: 'insensitive' as const } }] } : {}; const [items, total] = await Promise.all([prisma.user.findMany({ where, select: { id: true, fullName: true, email: true, studentCode: true, isEmailVerified: true, deletedAt: true, createdAt: true, roles: { include: { role: true } } }, skip: (query.page - 1) * query.limit, take: query.limit, orderBy: { createdAt: 'desc' } }), prisma.user.count({ where })]); return { items, pagination: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } }; }
export async function updateUser(id: string, input: { deletedAt?: Date | null; isEmailVerified?: boolean }) { const user = await prisma.user.findUnique({ where: { id } }); if (!user) throw serviceError('User not found', 404); return prisma.user.update({ where: { id }, data: input, select: { id: true, fullName: true, email: true, deletedAt: true, isEmailVerified: true } }); }
export async function feedback(status?: 'open' | 'in_progress' | 'resolved' | 'closed') { return prisma.feedback.findMany({ where: status ? { status } : {}, include: { user: { select: { id: true, fullName: true, email: true } } }, orderBy: { createdAt: 'desc' } }); }
export async function replyFeedback(id: string, input: { status: 'open' | 'in_progress' | 'resolved' | 'closed'; adminReply?: string | null }) { return prisma.feedback.update({ where: { id }, data: { ...input, resolvedAt: input.status === 'resolved' ? new Date() : null } }); }
export async function logs(query: { page: number; limit: number }) { const [items, total] = await Promise.all([prisma.activityLog.findMany({ include: { user: { select: { id: true, email: true, fullName: true } } }, orderBy: { createdAt: 'desc' }, skip: (query.page - 1) * query.limit, take: query.limit }), prisma.activityLog.count()]); return { items, pagination: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } }; }
export async function importTemplates(buffer: Buffer) { const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(buffer as unknown as never); const sheet = workbook.worksheets[0]; if (!sheet) throw serviceError('Excel workbook has no worksheet', 422); const templates: Array<{ code: string; name: string; credits: number }> = []; sheet.eachRow((row, index) => { if (index === 1) return; const code = String(row.getCell(1).value ?? '').trim(); const name = String(row.getCell(2).value ?? '').trim(); const credits = Number(row.getCell(3).value ?? 0); if (code && name && Number.isFinite(credits)) templates.push({ code, name, credits }); }); return { imported: templates.length, templates }; }
