import express from 'express';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { env } from './config/env.js';
import { requestId } from './middlewares/request-id.js';
import { requestLogger } from './middlewares/logger.js';
import { errorHandler, notFound } from './middlewares/error-handler.js';
import { healthRouter } from './routes/health.js';
import { authRouter } from './modules/auth/auth.routes.js';
import { usersRouter } from './modules/users/users.routes.js';
import { semestersRouter } from './modules/semesters/semesters.routes.js';
import { subjectsRouter } from './modules/subjects/subjects.routes.js';
import { studyPlansRouter } from './modules/study-plans/study-plans.routes.js';
import { tasksRouter } from './modules/tasks/tasks.routes.js';
import { kanbanRouter } from './modules/kanban/kanban.routes.js';
import { schedulesRouter } from './modules/schedules/schedules.routes.js';
import { eventsRouter } from './modules/events/events.routes.js';
import { calendarRouter } from './modules/calendar/calendar.routes.js';
import { goalsRouter } from './modules/goals/goals.routes.js';
import { dashboardRouter } from './modules/dashboard/dashboard.routes.js';
import { gradesRouter } from './modules/grades/grades.routes.js';
import { studySessionsRouter } from './modules/study-sessions/study-sessions.routes.js';
import { documentsRouter } from './modules/documents/documents.routes.js';
import { notesRouter } from './modules/notes/notes.routes.js';
import { notificationCronRouter, notificationsRouter, notificationSettingsRouter } from './modules/notifications/notifications.routes.js';
import { reportsRouter } from './modules/reports/reports.routes.js';
import { aiRouter } from './modules/ai/ai.routes.js';
import { flashcardsRouter } from './modules/flashcards/flashcards.routes.js';
import { groupsRouter } from './modules/groups/groups.routes.js';
import { adminRouter } from './modules/admin/admin.routes.js';
import { resolve } from 'node:path';

export const app = express();
app.set('trust proxy', env.TRUST_PROXY === 'true');
app.use(helmet());
app.use(cors({ origin: env.FRONTEND_URL.split(',').map((origin) => origin.trim()), credentials: true }));
app.use(rateLimit({ windowMs: 60_000, limit: 120, standardHeaders: true, legacyHeaders: false }));
app.use(express.json({ limit: '1mb', strict: true }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));
app.use(cookieParser());
app.use(requestId);
app.use(requestLogger);
app.use(healthRouter);
app.use('/api/auth', authRouter);
app.use('/api/users', usersRouter);
app.use('/api/semesters', semestersRouter);
app.use('/api/subjects', subjectsRouter);
app.use('/api/study-plans', studyPlansRouter);
app.use('/api/tasks', tasksRouter);
app.use('/api/kanban', kanbanRouter);
app.use('/api/schedules', schedulesRouter);
app.use('/api/events', eventsRouter);
app.use('/api/calendar', calendarRouter);
app.use('/api/goals', goalsRouter);
app.use('/api/dashboard', dashboardRouter);
app.use('/uploads', express.static(resolve(process.cwd(), 'uploads')));
app.get('/api', (_req, res) => res.json({ success: true, message: 'StudyFlow API', data: { version: '0.1.0' } }));
app.use('/api', gradesRouter);
app.use('/api', studySessionsRouter);
app.use('/api/documents', documentsRouter);
app.use('/api/notes', notesRouter);
app.use('/api/notifications', notificationsRouter);
app.use('/api/notification-settings', notificationSettingsRouter);
app.use('/api/cron', notificationCronRouter);
app.use('/api', reportsRouter);
app.use('/api/ai', aiRouter);
app.use('/api', flashcardsRouter);
app.use('/api/study-groups', groupsRouter);
app.use('/api/admin', adminRouter);
app.use(notFound);
app.use(errorHandler);
