import express from 'express';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { env } from './config/env.js';
import { requestId } from './middlewares/request-id.js';
import { requestLogger } from './middlewares/logger.js';
import { errorHandler, notFound } from './middlewares/error-handler.js';
import { healthRouter } from './routes/health.js';
import { authRouter } from './modules/auth/auth.routes.js';
import { usersRouter } from './modules/users/users.routes.js';
import { semestersRouter } from './modules/semesters/semesters.routes.js';
import { subjectsRouter } from './modules/subjects/subjects.routes.js';
import { studyPlansRouter } from './modules/study-plans/study-plans.routes.js';
import { tasksRouter } from './modules/tasks/tasks.routes.js';
import { kanbanRouter } from './modules/kanban/kanban.routes.js';
import { schedulesRouter } from './modules/schedules/schedules.routes.js';
import { eventsRouter } from './modules/events/events.routes.js';
import { calendarRouter } from './modules/calendar/calendar.routes.js';
import { goalsRouter } from './modules/goals/goals.routes.js';
import { dashboardRouter } from './modules/dashboard/dashboard.routes.js';
import { resolve } from 'node:path';

export const app = express();
app.set('trust proxy', env.TRUST_PROXY === 'true');
app.use(helmet());
app.use(cors({ origin: env.CLIENT_ORIGIN.split(',').map((origin) => origin.trim()), credentials: true }));
app.use(rateLimit({ windowMs: 60_000, limit: 120, standardHeaders: true, legacyHeaders: false }));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(requestId);
app.use(requestLogger);
app.use(healthRouter);
app.use('/api/auth', authRouter);
app.use('/api/users', usersRouter);
app.use('/api/semesters', semestersRouter);
app.use('/api/subjects', subjectsRouter);
app.use('/api/study-plans', studyPlansRouter);
app.use('/api/tasks', tasksRouter);
app.use('/api/kanban', kanbanRouter);
app.use('/api/schedules', schedulesRouter);
app.use('/api/events', eventsRouter);
app.use('/api/calendar', calendarRouter);
app.use('/api/goals', goalsRouter);
app.use('/api/dashboard', dashboardRouter);
app.use('/uploads', express.static(resolve(process.cwd(), 'uploads')));
app.get('/api', (_req, res) => res.json({ success: true, message: 'StudyFlow API', data: { version: '0.1.0' } }));
app.use(notFound);
app.use(errorHandler);
