import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import * as api from './tasks.api'

export const taskKeys = { all: ['tasks'] as const, list: (filters: api.TaskFilters) => ['tasks', filters] as const, detail: (id: string) => ['task', id] as const, plans: (filters: Record<string, string>) => ['study-plans', filters] as const }
export function useTasksQuery(filters: api.TaskFilters) { return useQuery({ queryKey: taskKeys.list(filters), queryFn: () => api.listTasks(filters) }) }
export function useTaskQuery(id: string) { return useQuery({ queryKey: taskKeys.detail(id), queryFn: () => api.getTask(id), enabled: Boolean(id) }) }
export function usePlansQuery(filters: Record<string, string>) { return useQuery({ queryKey: taskKeys.plans(filters), queryFn: () => api.listPlans(filters) }) }
export function useTaskStatusMutation() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, status }: { id: string; status: api.TaskStatus }) => api.updateTaskStatus(id, status), onMutate: async ({ id, status }) => { await client.cancelQueries({ queryKey: taskKeys.all }); const snapshots = client.getQueriesData({ queryKey: taskKeys.all }); snapshots.forEach(([key, old]) => { if (old && typeof old === 'object' && 'items' in old) client.setQueryData(key, { ...(old as object), items: (old as { items: api.Task[] }).items.map((task) => task.id === id ? { ...task, status } : task) }) }); const detail = client.getQueryData<api.TaskDetail>(taskKeys.detail(id)); client.setQueryData(taskKeys.detail(id), detail ? { ...detail, status } : detail); return { snapshots, detail } }, onError: (_error, input, context) => { context?.snapshots.forEach(([key, value]) => client.setQueryData(key, value)); client.setQueryData(taskKeys.detail(input.id), context?.detail) }, onSettled: (_data, _error, input) => { client.invalidateQueries({ queryKey: taskKeys.all }); client.invalidateQueries({ queryKey: taskKeys.detail(input.id) }) } }) }
export function useTaskCreateMutation() { const client = useQueryClient(); return useMutation({ mutationFn: api.createTask, onSuccess: () => client.invalidateQueries({ queryKey: taskKeys.all }) }) }
export function useSubtaskMutation() { const client = useQueryClient(); return useMutation({ mutationFn: ({ taskId, subtaskId, isDone }: { taskId: string; subtaskId: string; isDone: boolean }) => api.updateSubtask(taskId, subtaskId, isDone), onMutate: async ({ taskId, subtaskId, isDone }) => { await client.cancelQueries({ queryKey: taskKeys.detail(taskId) }); const previous = client.getQueryData<api.TaskDetail>(taskKeys.detail(taskId)); client.setQueryData(taskKeys.detail(taskId), previous ? { ...previous, subTasks: previous.subTasks.map((subtask) => subtask.id === subtaskId ? { ...subtask, isDone } : subtask) } : previous); return { previous } }, onError: (_error, input, context) => client.setQueryData(taskKeys.detail(input.taskId), context?.previous), onSettled: (_data, _error, input) => client.invalidateQueries({ queryKey: taskKeys.detail(input.taskId) }) }) }
export function useTaskDeleteMutation() { const client = useQueryClient(); return useMutation({ mutationFn: api.deleteTask, onSuccess: () => client.invalidateQueries({ queryKey: taskKeys.all }) }) }
export function useTaskDuplicateMutation() { const client = useQueryClient(); return useMutation({ mutationFn: api.duplicateTask, onSuccess: () => client.invalidateQueries({ queryKey: taskKeys.all }) }) }
