import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import * as api from './tasks.api'

export const taskKeys = { all: ['tasks'] as const, list: (filters: api.TaskFilters) => ['tasks', filters] as const, today: ['tasks', 'today'] as const, overdue: ['tasks', 'overdue'] as const, detail: (id: string) => ['task', id] as const, plans: (filters: Record<string, string>) => ['study-plans', filters] as const, planSummary: ['study-plans', 'summary'] as const }
export function useTasksQuery(filters: api.TaskFilters) { return useQuery({ queryKey: taskKeys.list(filters), queryFn: () => api.listTasks(filters) }) }
export function useTodayTasksQuery() { return useQuery({ queryKey: taskKeys.today, queryFn: api.listTodayTasks }) }
export function useOverdueTasksQuery() { return useQuery({ queryKey: taskKeys.overdue, queryFn: api.listOverdueTasks }) }
export function useTaskQuery(id: string) { return useQuery({ queryKey: taskKeys.detail(id), queryFn: () => api.getTask(id), enabled: Boolean(id) }) }
export function usePlansQuery(filters: Record<string, string>) { return useQuery({ queryKey: taskKeys.plans(filters), queryFn: () => api.listPlans(filters) }) }
export function usePlanSummaryQuery() { return useQuery({ queryKey: taskKeys.planSummary, queryFn: api.getPlanSummary }) }
export function useTaskStatusMutation() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, status }: { id: string; status: api.TaskStatus }) => api.updateTaskStatus(id, status), onMutate: async ({ id, status }) => { await client.cancelQueries({ queryKey: taskKeys.all }); const snapshots = client.getQueriesData({ queryKey: taskKeys.all }); snapshots.forEach(([key, old]) => { if (old && typeof old === 'object' && 'items' in old) client.setQueryData(key, { ...(old as object), items: (old as { items: api.Task[] }).items.map((task) => task.id === id ? { ...task, status } : task) }) }); const detail = client.getQueryData<api.TaskDetail>(taskKeys.detail(id)); client.setQueryData(taskKeys.detail(id), detail ? { ...detail, status } : detail); return { snapshots, detail } }, onError: (_error, input, context) => { context?.snapshots.forEach(([key, value]) => client.setQueryData(key, value)); client.setQueryData(taskKeys.detail(input.id), context?.detail) }, onSettled: () => { client.invalidateQueries({ queryKey: taskKeys.all }); client.invalidateQueries({ queryKey: ['dashboard'] }) } }) }
export function useTaskCreateMutation() { const client = useQueryClient(); return useMutation({ mutationFn: api.createTask, onSuccess: () => { client.invalidateQueries({ queryKey: taskKeys.all }); client.invalidateQueries({ queryKey: ['kanban'] }); client.invalidateQueries({ queryKey: ['dashboard'] }) } }) }
export function useTaskUpdateMutation() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: Partial<api.TaskInput> }) => api.updateTask(id, input), onSuccess: (data, input) => { client.invalidateQueries({ queryKey: taskKeys.all }); client.invalidateQueries({ queryKey: ['dashboard'] }); client.setQueryData<api.TaskDetail>(taskKeys.detail(input.id), (previous) => previous ? { ...previous, ...data, attachments: previous.attachments } : previous) } }) }
export function useTaskAttachmentMutation() { const client = useQueryClient(); return useMutation({ mutationFn: ({ taskId, file }: { taskId: string; file: File }) => api.uploadTaskAttachment(taskId, file), onSuccess: (data, input) => { const key = taskKeys.detail(input.taskId); client.setQueryData<api.TaskDetail>(key, (previous) => previous ? { ...previous, attachments: [...previous.attachments, data] } : previous) } }) }
export function useSubtaskMutation() { const client = useQueryClient(); return useMutation({ mutationFn: ({ taskId, subtaskId, isDone }: { taskId: string; subtaskId: string; isDone: boolean }) => api.updateSubtask(taskId, subtaskId, isDone), onMutate: async ({ taskId, subtaskId, isDone }) => { await client.cancelQueries({ queryKey: taskKeys.detail(taskId) }); const previous = client.getQueryData<api.TaskDetail>(taskKeys.detail(taskId)); client.setQueryData(taskKeys.detail(taskId), previous ? { ...previous, subTasks: previous.subTasks.map((subtask) => subtask.id === subtaskId ? { ...subtask, isDone } : subtask) } : previous); return { previous } }, onError: (_error, input, context) => client.setQueryData(taskKeys.detail(input.taskId), context?.previous), onSettled: (_data, _error, input) => { client.invalidateQueries({ queryKey: taskKeys.detail(input.taskId) }); client.invalidateQueries({ queryKey: taskKeys.all }); } }) }
export function useCreateSubtaskMutation() { const client = useQueryClient(); return useMutation({ mutationFn: ({ taskId, title }: { taskId: string; title: string }) => api.createSubtask(taskId, title), onSuccess: (_data, input) => { client.invalidateQueries({ queryKey: taskKeys.detail(input.taskId) }); client.invalidateQueries({ queryKey: taskKeys.all }); } }) }
export function useDeleteSubtaskMutation() { const client = useQueryClient(); return useMutation({ mutationFn: ({ taskId, subtaskId }: { taskId: string; subtaskId: string }) => api.deleteSubtask(taskId, subtaskId), onMutate: async ({ taskId, subtaskId }) => { await client.cancelQueries({ queryKey: taskKeys.detail(taskId) }); const previous = client.getQueryData<api.TaskDetail>(taskKeys.detail(taskId)); client.setQueryData(taskKeys.detail(taskId), previous ? { ...previous, subTasks: previous.subTasks.filter((subtask) => subtask.id !== subtaskId) } : previous); return { previous }; }, onError: (_error, input, context) => client.setQueryData(taskKeys.detail(input.taskId), context?.previous), onSettled: (_data, _error, input) => { client.invalidateQueries({ queryKey: taskKeys.detail(input.taskId) }); client.invalidateQueries({ queryKey: taskKeys.all }); } }) }
export function useTaskDeleteMutation() { const client = useQueryClient(); return useMutation({ mutationFn: api.deleteTask, onSuccess: () => { client.invalidateQueries({ queryKey: taskKeys.all }); client.invalidateQueries({ queryKey: ['kanban'] }); client.invalidateQueries({ queryKey: ['dashboard'] }) } }) }
export function useTaskDuplicateMutation() { const client = useQueryClient(); return useMutation({ mutationFn: api.duplicateTask, onSuccess: () => client.invalidateQueries({ queryKey: taskKeys.all }) }) }
export function usePlanCreateMutation() { const client = useQueryClient(); return useMutation({ mutationFn: api.createPlan, onSuccess: () => { client.invalidateQueries({ queryKey: ['study-plans'] }); client.invalidateQueries({ queryKey: ['dashboard'] }) } }) }
export function usePlanUpdateMutation() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: Partial<api.StudyPlanInput> }) => api.updatePlan(id, input), onSuccess: () => { client.invalidateQueries({ queryKey: ['study-plans'] }); client.invalidateQueries({ queryKey: ['dashboard'] }) } }) }
export function usePlanDeleteMutation() { const client = useQueryClient(); return useMutation({ mutationFn: api.deletePlan, onSuccess: () => { client.invalidateQueries({ queryKey: ['study-plans'] }); client.invalidateQueries({ queryKey: ['dashboard'] }) } }) }
