import { Check, CheckSquare, Copy, Filter, ListTodo, MoreHorizontal, Plus, Search, Trash2, X } from 'lucide-react'
import { useState } from 'react'
import toast from 'react-hot-toast'
import { Button, Checkbox, ConfirmDialog, Drawer, EmptyState, Input, Select, Skeleton } from '../components/ui'
import { useLearningSpacesQuery } from '../features/learning/learning.hooks'
import type { Task, TaskStatus } from '../features/tasks/tasks.api'
import { taskKeys, useSubtaskMutation, useTaskDeleteMutation, useTaskDuplicateMutation, useTaskQuery, useTasksQuery, useTaskStatusMutation } from '../features/tasks/tasks.hooks'
import { useQueryClient } from '@tanstack/react-query'

const statusLabels: Record<TaskStatus, string> = { todo: 'Chưa làm', in_progress: 'Đang làm', waiting: 'Chờ xử lý', done: 'Hoàn thành' }
const priorityLabels = { low: 'Thấp', medium: 'Vừa', high: 'Cao', urgent: 'Khẩn cấp' }
export function TasksPage() {
  const [filters, setFilters] = useState({ search: '', status: '', priority: '', dueDate: '', page: 1 })
  const [selected, setSelected] = useState<string[]>([]); const [drawerId, setDrawerId] = useState(''); const [removeId, setRemoveId] = useState('')
  const spaces = useLearningSpacesQuery(); const query = useTasksQuery({ ...filters, limit: 15 }); const statusMutation = useTaskStatusMutation(); const deleteMutation = useTaskDeleteMutation(); const duplicateMutation = useTaskDuplicateMutation(); const client = useQueryClient(); const tasks = query.data?.items ?? []
  const update = (key: keyof typeof filters, value: string) => setFilters((current) => ({ ...current, [key]: value, page: 1 }))
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const bulkStatus = (status: TaskStatus) => { selected.forEach((id) => statusMutation.mutate({ id, status })); setSelected([]); toast.success('Đã cập nhật các công việc') }
  return <div className="tasks-page">
    <div className="page-heading tasks-heading"><div><p className="eyebrow">NHỊP HỌC CỦA BẠN</p><h1>Công việc</h1><p className="subtle">Tập trung vào việc tiếp theo, dù bạn đang học hay làm một dự án riêng.</p></div><Button><Plus size={16} /> Tạo công việc</Button></div>
    <section className="panel task-toolbar"><label className="search-field"><Search size={16} /><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder="Tìm công việc..." aria-label="Tìm công việc" /></label><Select value={filters.status} onChange={(event) => update('status', event.target.value)} aria-label="Lọc trạng thái"><option value="">Mọi trạng thái</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Select value={filters.priority} onChange={(event) => update('priority', event.target.value)} aria-label="Lọc độ ưu tiên"><option value="">Mọi ưu tiên</option>{Object.entries(priorityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Input type="date" value={filters.dueDate} onChange={(event) => update('dueDate', event.target.value)} aria-label="Lọc hạn nộp" /></section>
    {selected.length > 0 && <div className="bulk-toolbar"><strong>{selected.length} việc đã chọn</strong><Button variant="secondary" onClick={() => bulkStatus('done')}><Check size={15} /> Hoàn thành</Button><Button variant="secondary" onClick={() => bulkStatus('in_progress')}>Đang làm</Button><button className="icon-button" onClick={() => setSelected([])} aria-label="Bỏ chọn"><X size={16} /></button></div>}
    {query.isLoading ? <div className="task-list-page">{[1, 2, 3].map((item) => <Skeleton key={item} height={72} />)}</div> : query.isError ? <EmptyState icon={<ListTodo size={24} />} title="Không thể tải công việc" description="Kiểm tra kết nối rồi thử lại." action={<Button onClick={() => query.refetch()}>Thử lại</Button>} /> : tasks.length === 0 ? <EmptyState icon={<CheckSquare size={24} />} title="Chưa có công việc" description="Tạo một việc nhỏ để bắt đầu nhịp học của bạn." action={<Button><Plus size={16} /> Tạo công việc</Button>} /> : <div className="task-list-page">{tasks.map((task) => <TaskRow key={task.id} task={task} checked={selected.includes(task.id)} onCheck={() => toggle(task.id)} onOpen={() => setDrawerId(task.id)} onStatus={(status) => statusMutation.mutate({ id: task.id, status })} onDelete={() => setRemoveId(task.id)} />)}</div>}
    {query.data && query.data.pagination.totalPages > 1 && <div className="task-pagination"><Button variant="secondary" disabled={filters.page <= 1} onClick={() => setFilters((current) => ({ ...current, page: current.page - 1 }))}>Trước</Button><span>Trang {filters.page} / {query.data.pagination.totalPages}</span><Button variant="secondary" disabled={filters.page >= query.data.pagination.totalPages} onClick={() => setFilters((current) => ({ ...current, page: current.page + 1 }))}>Sau</Button></div>}
    <TaskDrawer id={drawerId} onClose={() => setDrawerId('')} onDelete={(id) => { setDrawerId(''); setRemoveId(id) }} />
    <ConfirmDialog open={Boolean(removeId)} title="Xóa công việc?" description="Công việc sẽ được ẩn khỏi danh sách. Dữ liệu liên quan sẽ không còn hiển thị." onCancel={() => setRemoveId('')} onConfirm={() => deleteMutation.mutate(removeId, { onSuccess: () => { setRemoveId(''); toast.success('Đã xóa công việc') } })} loading={deleteMutation.isPending} />
  </div>
}
function TaskRow({ task, checked, onCheck, onOpen, onStatus, onDelete }: { task: Task; checked: boolean; onCheck: () => void; onOpen: () => void; onStatus: (status: TaskStatus) => void; onDelete: () => void }) { return <article className={`task-list-row task-status-${task.status}`}><input type="checkbox" checked={checked} onChange={onCheck} aria-label={`Chọn ${task.title}`} /><button className="task-row-main" onClick={onOpen}><span className="task-row-title">{task.title}</span><span className="task-row-meta">{task.dueDate ? new Date(task.dueDate).toLocaleDateString('vi-VN') : 'Chưa đặt hạn'} · {priorityLabels[task.priority]}</span></button><Select value={task.status} onChange={(event) => onStatus(event.target.value as TaskStatus)} aria-label={`Trạng thái ${task.title}`}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><button className="icon-button danger-icon" onClick={onDelete} aria-label={`Xóa ${task.title}`}><Trash2 size={16} /></button></article> }
function TaskDrawer({ id, onClose, onDelete }: { id: string; onClose: () => void; onDelete: (id: string) => void }) { const query = useTaskQuery(id); const subtaskMutation = useSubtaskMutation(); const duplicate = useTaskDuplicateMutation(); return <Drawer open={Boolean(id)} title={query.data?.title ?? 'Chi tiết công việc'} onClose={onClose}><div className="task-drawer-content">{query.isLoading ? <Skeleton height={300} /> : query.isError || !query.data ? <EmptyState title="Không thể tải công việc" description="Thử đóng rồi mở lại." /> : <><div className="drawer-task-status"><span className={`status-label task-pill-${query.data.status}`}>{statusLabels[query.data.status]}</span><span className={`priority priority-${query.data.priority}`}>{priorityLabels[query.data.priority]}</span></div>{query.data.description && <p className="drawer-description">{query.data.description}</p>}<div className="drawer-section"><h3>Việc nhỏ</h3>{query.data.subTasks.length ? query.data.subTasks.map((subtask) => <Checkbox key={subtask.id} label={subtask.title} checked={subtask.isDone} onChange={(event) => { const next = event.target.checked; clientOptimisticSubtask(subtaskMutation, query.data!.id, subtask.id, next) }} />) : <p className="subtle">Chưa có việc nhỏ.</p>}</div><div className="drawer-section"><h3>Tệp đính kèm</h3>{query.data.attachments.length ? query.data.attachments.map((file) => <a className="drawer-file" href={file.fileUrl} key={file.id}>{file.fileName}</a>) : <p className="subtle">Chưa có tệp đính kèm.</p>}</div><div className="drawer-actions"><Button variant="secondary" onClick={() => duplicate.mutate(query.data!.id, { onSuccess: () => toast.success('Đã nhân bản công việc') })}><Copy size={15} /> Nhân bản</Button><Button variant="danger" onClick={() => onDelete(query.data!.id)}><Trash2 size={15} /> Xóa</Button></div></>}</div></Drawer> }
function clientOptimisticSubtask(mutation: ReturnType<typeof useSubtaskMutation>, taskId: string, subtaskId: string, isDone: boolean) { mutation.mutate({ taskId, subtaskId, isDone }) }
