import { ArrowLeft, BookOpen, CalendarDays, CheckSquare, Clock3, FileText, Gauge, NotebookPen } from 'lucide-react'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { EmptyState, Skeleton, Tabs } from '../components/ui'
import { useTopicQuery } from '../features/learning/learning.hooks'

type DetailTab = 'overview' | 'calendar' | 'tasks' | 'documents' | 'progress' | 'notes' | 'time'
const tabs: Array<{ value: DetailTab; label: React.ReactNode }> = [{ value: 'overview', label: 'Tổng quan' }, { value: 'calendar', label: <><CalendarDays size={14} /> Lịch</> }, { value: 'tasks', label: <><CheckSquare size={14} /> Bài tập</> }, { value: 'documents', label: <><FileText size={14} /> Tài liệu</> }, { value: 'progress', label: <><Gauge size={14} /> Tiến độ</> }, { value: 'notes', label: <><NotebookPen size={14} /> Ghi chú</> }, { value: 'time', label: <><Clock3 size={14} /> Thời gian học</> }]

export function TopicDetailPage() { const { id = '' } = useParams(); const [tab, setTab] = useState<DetailTab>('overview'); const query = useTopicQuery(id); if (query.isLoading) return <div className="topic-detail"><Skeleton height={260} /></div>; if (query.isError || !query.data) return <EmptyState title="Không thể tải chủ đề" description="Chủ đề có thể đã bị xóa hoặc bạn không có quyền truy cập." action={<Link className="button secondary" to="/topics">Quay lại chủ đề</Link>} />; const topic = query.data; return <div className="topic-detail"><Link className="back-link" to="/topics"><ArrowLeft size={15} /> Quay lại chủ đề</Link><header className="topic-detail-head" style={{ borderLeftColor: topic.colorHex }}><div><p className="eyebrow">{topic.code}</p><h1>{topic.name}</h1><p className="subtle">{topic.credits} đơn vị theo dõi · {topic.status === 'completed' ? 'Đã hoàn thành' : 'Đang theo dõi'}</p></div><span className="topic-detail-mark" style={{ background: topic.colorHex }}><BookOpen size={22} /></span></header><Tabs value={tab} onChange={setTab} items={tabs} />{tab === 'overview' ? <section className="topic-stats"><Stat label="Việc đã tạo" value={topic.statistics.taskTotal} icon={<CheckSquare size={18} />} /><Stat label="Việc hoàn thành" value={topic.statistics.taskDone} icon={<Gauge size={18} />} /><Stat label="Thời gian học" value={`${topic.statistics.totalStudyMinutes} phút`} icon={<Clock3 size={18} />} /><Stat label="Điểm hiện tại" value={topic.statistics.currentAverage ?? '—'} icon={<NotebookPen size={18} />} /></section> : <section className="panel topic-tab-empty"><EmptyState icon={tabs.find((item) => item.value === tab)?.label} title="Khu vực đang được chuẩn bị" description="Dữ liệu của tab này sẽ được tải khi module tương ứng được triển khai." /></section>}</div> }
function Stat({ label, value, icon }: { label: string; value: string | number; icon: React.ReactNode }) { return <div className="stat-card topic-stat"><span className="stat-icon blue">{icon}</span><span className="stat-label">{label}</span><strong className="stat-value">{value}</strong></div> }
