import React from 'react'
import ReactDOM from 'react-dom/client'
import { RouterProvider } from 'react-router-dom'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { Toaster } from 'react-hot-toast'
import { router } from './routes/config'
import { AppErrorBoundary } from './components/AppErrorBoundary'
import './styles/index.css'
import './styles/dark-mode.css'
import './styles/dashboard.css'
import './styles/learning.css'
import './styles/tasks.css'
import './styles/task-drawer.css'
import './styles/dashboard-complete.css'
import './styles/bulk-controls.css'
import './styles/kanban.css'
import './styles/kanban-overrides.css'
import './styles/calendar.css'
import './styles/topbar.css'
import './styles/dashboard-upcoming.css'
import './styles/sidebar-tip.css'
import './styles/plan-date-picker.css'
import './styles/study.css'
import './styles/goals.css'
import './styles/notifications.css'
import './styles/documents-notes.css'
import './styles/statistics.css'
import './styles/ai-flashcards.css'
import './styles/groups-admin.css'
import './styles/quality.css'
import './styles/auth-destination.css'
import './styles/nature-theme.css'
import './styles/nature-components.css'
import './styles/app-shell.css'

const queryClient = new QueryClient({ defaultOptions: { queries: { staleTime: 30_000, retry: 1 } } })
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AppErrorBoundary><QueryClientProvider client={queryClient}><RouterProvider router={router} /><Toaster position="top-right" /></QueryClientProvider></AppErrorBoundary></React.StrictMode>)
