import { prisma } from '../../lib/prisma.js';
import { serviceError } from '../../utils/service-error.js';
async function setOwned(userId: string, id: string) { const item = await prisma.flashcardSet.findFirst({ where: { id, userId } }); if (!item) throw serviceError('Flashcard set not found', 404); return item; }
async function cardOwned(userId: string, id: string) { const item = await prisma.flashcard.findFirst({ where: { id, flashcardSet: { userId } } }); if (!item) throw serviceError('Flashcard not found', 404); return item; }
async function subject(userId: string, id?: string | null) { if (!id) return; const item = await prisma.subject.findFirst({ where: { id, userId, deletedAt: null } }); if (!item) throw serviceError('Subject not found', 404); }
export async function listSets(userId: string) { return prisma.flashcardSet.findMany({ where: { userId }, include: { _count: { select: { flashcards: true } } }, orderBy: { updatedAt: 'desc' } }); }
export async function createSet(userId: string, input: { subjectId?: string | null; name: string; description?: string | null }) { await subject(userId, input.subjectId); return prisma.flashcardSet.create({ data: { ...input, userId } }); }
export async function detailSet(userId: string, id: string) { await setOwned(userId, id); return prisma.flashcardSet.findUnique({ where: { id }, include: { flashcards: { orderBy: { createdAt: 'asc' } } } }); }
export async function updateSet(userId: string, id: string, input: { subjectId?: string | null; name?: string; description?: string | null }) { await setOwned(userId, id); await subject(userId, input.subjectId); return prisma.flashcardSet.update({ where: { id }, data: input }); }
export async function removeSet(userId: string, id: string) { await setOwned(userId, id); await prisma.flashcardSet.delete({ where: { id } }); return { id }; }
export async function listCards(userId: string, setId: string) { await setOwned(userId, setId); return prisma.flashcard.findMany({ where: { flashcardSetId: setId }, orderBy: { createdAt: 'asc' } }); }
export async function createCard(userId: string, setId: string, input: { question: string; answer: string; isDifficult?: boolean }) { await setOwned(userId, setId); return prisma.flashcard.create({ data: { ...input, flashcardSetId: setId } }); }
export async function updateCard(userId: string, id: string, input: { question?: string; answer?: string; isDifficult?: boolean }) { await cardOwned(userId, id); return prisma.flashcard.update({ where: { id }, data: input }); }
export async function removeCard(userId: string, id: string) { await cardOwned(userId, id); await prisma.flashcard.delete({ where: { id } }); return { id }; }
export async function review(userId: string, id: string, correct: boolean) { const card = await cardOwned(userId, id); const correctCount = card.correctCount + (correct ? 1 : 0); const wrongCount = card.wrongCount + (correct ? 0 : 1); const interval = correct ? [1, 3, 7, 14, 30][Math.min(correctCount - 1, 4)] : 0.007; const nextReviewAt = new Date(Date.now() + interval * 86_400_000); return prisma.flashcard.update({ where: { id }, data: { correctCount, wrongCount, isDifficult: correct ? card.isDifficult : true, nextReviewAt } }); }
export async function due(userId: string) { return prisma.flashcard.findMany({ where: { flashcardSet: { userId }, OR: [{ nextReviewAt: null }, { nextReviewAt: { lte: new Date() } }] }, include: { flashcardSet: { select: { id: true, name: true } } }, orderBy: { nextReviewAt: 'asc' } }); }
