import { prisma } from '../../lib/prisma.js';
import { serviceError } from '../../utils/service-error.js';
async function groupAccess(userId: string, id: string, ownerOnly = false) { const group = await prisma.studyGroup.findUnique({ where: { id }, include: { members: true, tasks: true } }); if (!group || (ownerOnly ? group.ownerId !== userId : group.ownerId !== userId && !group.members.some((m) => m.userId === userId && m.status === 'accepted'))) throw serviceError('Study group not found or access denied', 404); return group; }
export async function list(userId: string) { return prisma.studyGroup.findMany({ where: { OR: [{ ownerId: userId }, { members: { some: { userId, status: 'accepted' } } }] }, include: { _count: { select: { members: true, tasks: true } } }, orderBy: { updatedAt: 'desc' } }); }
export async function create(userId: string, input: { name: string; description?: string | null }) { return prisma.studyGroup.create({ data: { ...input, ownerId: userId, members: { create: { userId, role: 'leader', status: 'accepted', joinedAt: new Date() } } }, include: { members: true } }); }
export async function detail(userId: string, id: string) { await groupAccess(userId, id); return prisma.studyGroup.findUnique({ where: { id }, include: { members: { include: { user: { select: { id: true, fullName: true, email: true } } } }, tasks: true } }); }
export async function update(userId: string, id: string, input: { name?: string; description?: string | null }) { await groupAccess(userId, id, true); return prisma.studyGroup.update({ where: { id }, data: input }); }
export async function remove(userId: string, id: string) { await groupAccess(userId, id, true); await prisma.studyGroup.delete({ where: { id } }); return { id }; }
export async function invite(userId: string, id: string, invitedUserId: string) { await groupAccess(userId, id, true); const user = await prisma.user.findFirst({ where: { id: invitedUserId, deletedAt: null } }); if (!user) throw serviceError('User not found', 404); return prisma.groupMember.upsert({ where: { studyGroupId_userId: { studyGroupId: id, userId: invitedUserId } }, create: { studyGroupId: id, userId: invitedUserId }, update: { status: 'pending', joinedAt: null } }); }
export async function accept(userId: string, id: string, memberId: string) { const member = await prisma.groupMember.findFirst({ where: { id: memberId, studyGroupId: id, userId } }); if (!member) throw serviceError('Invitation not found', 404); return prisma.groupMember.update({ where: { id: memberId }, data: { status: 'accepted', joinedAt: new Date() } }); }
export async function createTask(userId: string, groupId: string, input: { assignedUserId?: string | null; title: string; description?: string | null; dueDate?: Date | null; status?: 'todo' | 'in_progress' | 'waiting' | 'done' }) { const group = await groupAccess(userId, groupId); if (input.assignedUserId && !group.members.some((m) => m.userId === input.assignedUserId && m.status === 'accepted')) throw serviceError('Assigned user is not an active member', 422); return prisma.groupTask.create({ data: { ...input, studyGroupId: groupId } }); }
export async function updateTask(userId: string, id: string, input: object) { const task = await prisma.groupTask.findUnique({ where: { id } }); if (!task) throw serviceError('Group task not found', 404); await groupAccess(userId, task.studyGroupId); return prisma.groupTask.update({ where: { id }, data: input }); }
export async function progress(userId: string, id: string) { const group = await groupAccess(userId, id); const total = group.tasks.length; const done = group.tasks.filter((task) => task.status === 'done').length; return { groupId: id, totalTasks: total, doneTasks: done, progressPercent: total ? Math.round(done / total * 10000) / 100 : 0 }; }
